/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2023-02-03 14:37:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class complex_005fform_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-6.0.1.jar", Long.valueOf(1675028775635L));
    _jspx_dependants.put("jar:file:/home/arbab/Desktop/Spring-core/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/springmvcsearch/WEB-INF/lib/spring-webmvc-6.0.1.jar!/META-INF/spring-form.tld", Long.valueOf(1669179538000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fform_005ferrors_0026_005fpath_005fnobody;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fform_005ferrors_0026_005fpath_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fform_005ferrors_0026_005fpath_005fnobody.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("    \n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC\" crossorigin=\"anonymous\">\n");
      out.write("<title>ComplexForm</title>\n");
      out.write("</head>\n");
      out.write("<body class=\"\" style=\"background: #e2e2e2;\">\n");
      out.write("	\n");
      out.write("	<div class=\"container mt-4\">\n");
      out.write("		\n");
      out.write("		<div class=\"row\">\n");
      out.write("			<div class=\"col-md-8 offset-md-2\">\n");
      out.write("				<div class=\"card\">\n");
      out.write("					<div class=\"card-body\">\n");
      out.write("						<h3 class=\"text-center\">Complex Form</h3>\n");
      out.write("						\n");
      out.write("						<div class=\"alert alert-danger\" role=\"alert\">\n");
      out.write("						\n");
      out.write("						");
      //  form:errors
      org.springframework.web.servlet.tags.form.ErrorsTag _jspx_th_form_005ferrors_005f0 = (org.springframework.web.servlet.tags.form.ErrorsTag) _005fjspx_005ftagPool_005fform_005ferrors_0026_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.ErrorsTag.class);
      boolean _jspx_th_form_005ferrors_005f0_reused = false;
      try {
        _jspx_th_form_005ferrors_005f0.setPageContext(_jspx_page_context);
        _jspx_th_form_005ferrors_005f0.setParent(null);
        // /WEB-INF/views/complex_form.jsp(26,6) name = path type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_form_005ferrors_005f0.setPath("student.*");
        int[] _jspx_push_body_count_form_005ferrors_005f0 = new int[] { 0 };
        try {
          int _jspx_eval_form_005ferrors_005f0 = _jspx_th_form_005ferrors_005f0.doStartTag();
          if (_jspx_th_form_005ferrors_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            return;
          }
        } catch (java.lang.Throwable _jspx_exception) {
          while (_jspx_push_body_count_form_005ferrors_005f0[0]-- > 0)
            out = _jspx_page_context.popBody();
          _jspx_th_form_005ferrors_005f0.doCatch(_jspx_exception);
        } finally {
          _jspx_th_form_005ferrors_005f0.doFinally();
        }
        _005fjspx_005ftagPool_005fform_005ferrors_0026_005fpath_005fnobody.reuse(_jspx_th_form_005ferrors_005f0);
        _jspx_th_form_005ferrors_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_form_005ferrors_005f0, _jsp_getInstanceManager(), _jspx_th_form_005ferrors_005f0_reused);
      }
      out.write("\n");
      out.write(" 						 \n");
      out.write("						</div>\n");
      out.write("						\n");
      out.write("					<form action=\"handleform\" method=\"post\">\n");
      out.write("						  <div class=\"form-group mt-3\">\n");
      out.write("						    <label for=\"exampleInputEmail1\">Your name</label>\n");
      out.write("						    <input \n");
      out.write("						    name=\"name\" type=\"text\" class=\"form-control\" \n");
      out.write("						    id=\"exampleInputEmail1\" aria-describedby=\"emailHelp\" \n");
      out.write("						    placeholder=\"Enter Name\">\n");
      out.write("						    <small id=\"emailHelp\" class=\"form-text text-muted\">We'll never share your name with anyone else.</small>\n");
      out.write("						  </div>\n");
      out.write("						  \n");
      out.write("						    <div class=\"form-group mt-3\">\n");
      out.write("						    <label for=\"exampleInputEmail1\">Your Id</label>\n");
      out.write("						    <input \n");
      out.write("						    name=\"id\" type=\"text\" class=\"form-control\" \n");
      out.write("						    id=\"exampleInputEmail1\" aria-describedby=\"emailHelp\" \n");
      out.write("						    placeholder=\"Enter Name\">\n");
      out.write("						  </div>\n");
      out.write("						  \n");
      out.write("						  \n");
      out.write("						    <div class=\"form-group mt-3\">\n");
      out.write("						    <label for=\"exampleInputEmail1\">Your DOB</label>\n");
      out.write("						    <input \n");
      out.write("						    name=\"date\" type=\"date\" class=\"form-control\" \n");
      out.write("						    id=\"exampleInputEmail1\" aria-describedby=\"emailHelp\" \n");
      out.write("						    placeholder=\"dd/mm/yyyy\">\n");
      out.write("						  </div>\n");
      out.write("						  \n");
      out.write("						    <div class=\"form-group mt-3\">\n");
      out.write("						    <label for=\"exampleInputEmail1\">Select courses</label>\n");
      out.write("						    <select\n");
      out.write("						    name=\"courses\" class=\"form-control\" \n");
      out.write("						    id=\"exampleInputEmail1\" aria-describedby=\"emailHelp\" \n");
      out.write("						    >\n");
      out.write("						    <option >Java</option>\n");
      out.write(" 							<option>Python</option>\n");
      out.write("  							<option>C++</option>\n");
      out.write("  							<option>Django</option>\n");
      out.write("  							<option>Spring Framework</option>\n");
      out.write("  							\n");
      out.write("						    </select>\n");
      out.write("						  </div>\n");
      out.write("							\n");
      out.write("							<div class=\"form-group mt-3\">\n");
      out.write("								<span class=\"mr-3\">Select Gender</span>\n");
      out.write("								<div class=\"form-check form-check-inline\">\n");
      out.write("									<input class=\"form-check form-check-inline\" type=\"radio\" name=\"gender\"\n");
      out.write("										id=\"inlineRadio1\" value=\"male\">\n");
      out.write("									<label\n");
      out.write("										class=\"form-check-lable\" for=\"inlineRadio1\"\n");
      out.write("									>Male</label>\n");
      out.write("									\n");
      out.write("								</div>\n");
      out.write("								<div class=\"form-check form-check-inline mt-3\">\n");
      out.write("									<input class=\"form-check form-check-inline\" type=\"radio\" name=\"gender\"\n");
      out.write("										id=\"inlineRadio1\" value=\"female\">\n");
      out.write("									<label\n");
      out.write("										class=\"form-check-lable\" for=\"inlineRadio1\"\n");
      out.write("									>Female</label>\n");
      out.write("									\n");
      out.write("								</div>\n");
      out.write("								    <div class=\"form-group mt-3\">\n");
      out.write("						    <label for=\"exampleInputEmail1\">Select Type</label>\n");
      out.write("						    <select\n");
      out.write("						    name=\"type\" class=\"form-control\" \n");
      out.write("						    id=\"exampleInputEmail1\" aria-describedby=\"emailHelp\" \n");
      out.write("						    >\n");
      out.write("						    <option value=\"oldstudent\" >Old student</option>\n");
      out.write(" 							<option value=\"normalstudent\">Normal Student</option>\n");
      out.write("						    </select>\n");
      out.write("						  </div>\n");
      out.write("							</div>\n");
      out.write("							\n");
      out.write("							<div class=\"card\">\n");
      out.write("							\n");
      out.write("							<div class=\"card-body \">\n");
      out.write("								<p>Your address</p>\n");
      out.write("								<div class=\"form-group\">\n");
      out.write("								<input\n");
      out.write("								\n");
      out.write("								name=\"address.street\" \n");
      out.write("								type=\"text\" \n");
      out.write("								class=\"form-control\" \n");
      out.write("								placeholder=\"Enter street\">\n");
      out.write("								\n");
      out.write("								</div>\n");
      out.write("								\n");
      out.write("								\n");
      out.write("								<div class=\"form-group\">\n");
      out.write("								<input \n");
      out.write("								name=\"address.city\"\n");
      out.write("								type=\"text\" \n");
      out.write("								class=\"form-control\" \n");
      out.write("								placeholder=\"Enter city\">\n");
      out.write("								\n");
      out.write("								</div>\n");
      out.write("								\n");
      out.write("							</div>\n");
      out.write("							</div>\n");
      out.write("						  <div class=\"form-group form-check text-center mt-3\">\n");
      out.write("										  <button type=\"submit\" class=\"btn btn-primary\">Submit</button>\n");
      out.write("				\n");
      out.write("						  </div>\n");
      out.write("						</form>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			\n");
      out.write("			</div>\n");
      out.write("			\n");
      out.write("		</div>\n");
      out.write("		\n");
      out.write("	</div>\n");
      out.write("	\n");
      out.write("	\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
